events {}

http {
    server {
        listen 80;

        # PORTAL (ton site HTML)
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # EPARVIER API
        location /eparvier/api/ {
            proxy_pass http://eparvier-api:80/;
        }

        # EPARVIER Cockpit
        location /eparvier/cockpit/ {
            proxy_pass http://eparvier-blazor:80/;
        }

        # KINGDOMAINE
        location /kingdomaine/ {
            proxy_pass http://kingdomaine:80/;
        }

        # PROMETHEUS
        location /monitoring/prometheus/ {
            proxy_pass http://prometheus:9090/;
        }

        # BLACKBOX
        location /monitoring/blackbox/ {
            proxy_pass http://blackbox_exporter:9115/;
        }

        # GRAFANA
        location /monitoring/grafana/ {
            proxy_pass http://grafana:3000/;
        }
    }
}
