version: "3.9"

services:
  loki:
    image: grafana/loki:2.9.3
    container_name: kingao-loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - kingao-net

  promtail:
    image: grafana/promtail:latest
    container_name: kingao-promtail
    restart: always
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
    networks:
      - kingao-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: eparvier-alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - kingao-net

networks:
  kingao-net:
    external: true
