[PATHS]
ROOT=/opt/KING-AO/KING-AO
ACTIONS=/opt/KING-AO/KING-AO/actions
MODULES=/opt/KING-AO/modules
LOGS=/opt/KING-AO/KING-AO/logs
CONFIG=/opt/KING-AO/KING-AO/config

# Modules KING-AO
PORTAL=/opt/KING-AO/modules/portal
COCKPIT=/opt/KING-AO/KING-AO/cockpit

METIER=/opt/KING-AO/modules/metier
KINGDOMAINE=/opt/KING-AO/modules/kingdomaine
MONGODB=/opt/KING-AO/modules/mongodb

# EPARVIER — multi-projets
EPARVIER_API=/opt/KING-AO/modules/EPARVIER
EPARVIER_COCKPIT=/opt/KING-AO/modules/EPARVIER/SolaizeCockpit
SHARED=/opt/KING-AO/modules/EPARVIER/Solaize.Shared



