# ============================================================
# 🟦 MODULES PRINCIPAUX KING-AO
# ============================================================
PORTAL=/opt/KING-AO/modules/portal
COCKPIT=/opt/KING-AO/KING-AO/cockpit

EPARVIER=/opt/KING-AO/modules/EPARVIER
EPARVIER_API=/opt/KING-AO/modules/EPARVIER/SolaizeApi
EPARVIER_COCKPIT=/opt/KING-AO/modules/EPARVIER/SolaizeCockpit
EPARVIER_SHARED=/opt/KING-AO/modules/EPARVIER/Solaize.Shared
EPARVIER_DOCKER=/opt/KING-AO/modules/EPARVIER/docker


# 👉 Si un jour tu ajoutes un autre projet partagé :
# SHARED2=/opt/KING-AO/modules/EPARVIER/Solaize.Shared2
# SHARED3=/opt/KING-AO/modules/EPARVIER/Solaize.Shared3



