[PATHS]
ROOT=/opt/KING-AO/KING-AO
ACTIONS=/opt/KING-AO/KING-AO/actions
MODULES=/opt/KING-AO/KING-AO/modules
LOGS=/opt/KING-AO/KING-AO/logs
CONFIG=/opt/KING-AO/KING-AO/config
PORTAL=/opt/KING-AO/KING-AO/modules/portal
COCKPIT=/opt/KING-AO/KING-AO/cockpit
METIER=/opt/KING-AO/modules/metier
KINGDOMAINE=/opt/KING-AO/modules/kingdomaine
NETWORKING=/opt/KING-AO/modules/networking




