version: "3.9"

services:
  kingdomaine-api:
    image: kingdomaine:latest
    container_name: kingdomaine-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5010:80"
    networks:
      - kingao-net

networks:
  kingao-net:
    external: true

