version: '3.8'

services:

  eparvier-api:
    image: solaizeapi
    container_name: eparvier-api
    restart: unless-stopped
    ports:
      - "5010:80"
    networks:
      - kingao-net

  eparvier-cockpit:
    image: solaizecockpit
    container_name: eparvier-cockpit
    restart: unless-stopped
    ports:
      - "5011:80"
    networks:
      - kingao-net

  blackbox:
    image: prom/blackbox-exporter
    container_name: eparvier-blackbox
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - "9115:9115"
    networks:
      - kingao-net

  prometheus:
    image: prom/prometheus
    container_name: eparvier-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - kingao-net

  alertmanager:
    image: prom/alertmanager
    container_name: eparvier-alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - kingao-net

networks:
  kingao-net:
    external: true
