FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Solaize.Shared/Solaize.Shared.csproj Solaize.Shared/
COPY SolaizeApi/SolaizeApi.csproj SolaizeApi/

RUN dotnet restore SolaizeApi/SolaizeApi.csproj

COPY . .

RUN dotnet publish SolaizeApi/SolaizeApi.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "SolaizeApi.dll"]
