FROM node:20-alpine AS build

WORKDIR /app

COPY . .

WORKDIR /app/apps/KINGDomaineCockpit

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/apps/KINGDomaineCockpit/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]