version: "3.9"

services:
  mongo_eparvier:
    image: mongo:latest
    container_name: mongo_eparvier
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_eparvier_data:/data/db
    networks:
      - kingao-net

  eparvier-api:
    image: solaizeapi:latest
    container_name: eparvier-api
    restart: always
    depends_on:
      - mongo_eparvier
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MONGO_URL=mongodb://mongo_eparvier:27017
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kingao-net

  eparvier-cockpit:
    image: solaizecockpit:latest
    container_name: eparvier-cockpit
    restart: always
    ports:
      - "5011:80"
    networks:
      - kingao-net

volumes:
  mongo_eparvier_data:

networks:
  kingao-net:
    external: true
