version: "3.9"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: kingao-cadvisor
    restart: always
    ports:
      - "8080:8080"
    networks:
      - kingao-net

  prometheus:
    image: prom/prometheus:latest
    container_name: kingao-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kingao-net

  grafana:
    image: grafana/grafana:latest
    container_name: kingao-grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - kingao-net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    networks:
      - kingao-net

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: always
    ports:
      - "9115:9115"
    networks:
      - kingao-net

  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb_exporter
    restart: always
    ports:
      - "9216:9216"
    networks:
      - kingao-net

networks:
  kingao-net:
    external: true
