 version: "3.9"

services:

  kingdomaine-api:
    container_name: kingdomaine-api
    build:
      context: ./KINGDomaineApi
      dockerfile: Dockerfile.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5002:5002"
    networks:
      - king-ao-net
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/domaine/status"]
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - ./data/uploads:/app/uploads


  metier-api:
    container_name: metier-api
    build:
      context: ./METIERApi
      dockerfile: Dockerfile.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5003:5003"
    networks:
      - king-ao-net
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/api/metier/status"]
      interval: 10s
      timeout: 3s
      retries: 5


  eparvier-api:
    container_name: eparvier-api
    build:
      context: ./EPARVIERApi
      dockerfile: Dockerfile.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5004:5004"
    networks:
      - king-ao-net
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/api/eparvier/status"]
      interval: 10s
      timeout: 3s
      retries: 5


  portal:
    container_name: king-portal
    build:
      context: ./PORTAL
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - king-ao-net
    restart: unless-stopped


networks:
  king-ao-net:
    driver: bridge
