version: "3.9"

services:
  kingdomaine-cockpit:
    image: kingdomaine-cockpit:latest
    container_name: kingdomaine-cockpit
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5011:80"
    networks:
      - kingao-net

networks:
  kingao-net:
    external: true
